server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/help_desk_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: connect.smtp.bz
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      thread_count: ${SPRING_MAIL_TREAD_COUNT}
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  password:
    encoder:
      secret: ${JWT_PASSWORD_SECRET}
      iteration: 64
      key-length: 256
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: HELP_DESK

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.praktica.HelpDesk.controller

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true